### ISSUE TITLE
http://coshsh.org/ shows default nginx page

### ISSUE THREAD

**Issue by Velociraptor85** [lausser/coshsh#6]
http://coshsh.org/ shows default nginx page 

![grafik](https://user-images.githubusercontent.com/4143960/64588552-0182f380-d3a3-11e9-9815-a09168aee4fd.png)

I would expect something more as there is a link in your ![Readme.md](https://github.com/lausser/coshsh#what-is-coshsh)

**Comment by lausser** [comment]
Done
